name: 30 License Compliance

on:
  workflow_dispatch:
  workflow_call:

jobs:
  license-finder:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      # Ensure all dependencies are downloaded by building the project
      - name: 'Build Project and Download Dependencies'
        run: mvn dependency:go-offline

      - name: 'License Finder'
        uses: jmservera/license-finder-action@main
        with:
          permitted-licenses: MIT,Apache-2.0,BSD,EPL1
          approved-dependencies: |
            hamcrest,hamcrest-core,hamcrest-library
            junit-jupiter,junit-jupiter-api,junit-jupiter-engine,javax.annotation-api

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.2.0
        if: always()
        with:
          junit_files: "license_finder_report.xml"
          check_name: "License Compliance Check"

      - name: 'Upload Dependency Review Report'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: license-finder-report
          path: ${{ github.workspace }}/license_finder_report.xml

