name: 20 SCA

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sca:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-20.04" ] # You can add ["macos-latest", "windows-latest"] if needed
        manifest_file: [ "pom.xml" ] # Add more manifest files as needed
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    name: SCA Java project
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Scan
        id: snyk_scan
        run: snyk test --file=${{ matrix.manifest_file }} --json > snyk_report.json
        env:
          SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}

      - name: Print Snyk JSON analysis report
        if: ${{ always() }}
        run: cat snyk_report.json

      - name: Upload Snyk report as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk_report
          path: snyk_report.json

      - name: Monitor vulnerabilities (optional)
        run: snyk monitor --file=${{ matrix.manifest_file }}
        env:
          SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}
